module.exports = [
  {
    id: '1',
    title: 'Big Buck Bunny',
    description: 'A large, fluffy bunny is rudely awakened by three rodents.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Big_Buck_Bunny_small.jpg/1200px-Big_Buck_Bunny_small.jpg',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 4.5,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Sintel',
    description: 'A courageous girl named Sintel embarks on a perilous journey.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sintel_movie_logo.jpg/1200px-Sintel_movie_logo.jpg',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    rating: 4.8,
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Tears of Steel',
    description: 'A group of scientists and artists are trying to bring a deceased woman back to life.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Tears_of_Steel_screenshot_robot.jpg/1200px-Tears_of_Steel_screenshot_robot.jpg',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    rating: 4.2,
    isFeatured: false,
  },
  {
    id: '4',
    title: 'Elephant Dream',
    description: 'Two characters explore a surreal world.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Elephants_Dream_by_Blender_Foundation.jpg/1200px-Elephants_Dream_by_Blender_Foundation.jpg',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    rating: 3.9,
    isFeatured: false,
  },
  {
    id: '5',
    title: 'For Bigger Blazes',
    description: 'A short film about fire.',
    imageUrl: 'https://via.placeholder.com/300x200?text=For+Bigger+Blazes',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    rating: 4.0,
    isFeatured: true,
  },
  {
    id: '6',
    title: 'For Bigger Escape',
    description: 'A short film about escaping.',
    imageUrl: 'https://via.placeholder.com/300x200?text=For+Bigger+Escape',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscape.mp4',
    rating: 4.1,
    isFeatured: false,
  },
  {
    id: '7',
    title: 'For Bigger Joyrides',
    description: 'A short film about joyrides.',
    imageUrl: 'https://via.placeholder.com/300x200?text=For+Bigger+Joyrides',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    rating: 4.3,
    isFeatured: true,
  },
  {
    id: '8',
    title: 'For Bigger Fun',
    description: 'A short film about having fun.',
    imageUrl: 'https://via.placeholder.com/300x200?text=For+Bigger+Fun',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    rating: 4.6,
    isFeatured: false,
  }
];
